### ISSUE TITLE
Unhandled Exception: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by dogancelik** [zumoshi/BrowserSelect#17]
I don't have Visual Studio to debug right now, meanwhile I would like to post it here:

I get this error when I open any URL

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at BrowserSelect.BrowserUC..ctor(Browser b, Int32 index)
   at BrowserSelect.Form1.Form1_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
BrowserSelect
    Assembly Version: 1.3.4.0
    Win32 Version: 1.3.4.0
    CodeBase: file:///C:/Users/dogan/AppData/Local/BrowserSelect/BrowserSelect.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by zumoshi** [comment]
hello,
could you please run [this bat file](https://gist.githubusercontent.com/zumoshi/39c4c04b6d770539964006d10d286ab0/raw/b3e8fbd93b466b3185961106fdae401cf449e61f/registry.bat) and post the txt file that it creates ?

it dumps the contents of this registry key in a txt file:
```
HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet
```

the issue you mentioned may be caused by an incomplete record in that key , for example, if a browser is not completely removed upon uninstallation and left some leftovers in the registry.

some versions of `Browser Chooser` are known to cause this.

**Comment by dogancelik** [comment]
[I posted export.txt here](https://gist.githubusercontent.com/dogancelik/c7b6e37cb11310c2443b1da9f3ec273e/raw/ffdf7634cc197c16cc9a77a16f0a569688386e6f/export.txt)

I have Google Chrome Canary too and it is not detecting Canary (its code name is Chrome SxS).

**Comment by zumoshi** [comment]
based on your export.txt i think internet explorer is causing the issue.
can you try removing this key and see if it solves the problem ?

`HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\IEXPLORE.EXE`

the only side effect this can have is to remove/hide IE from browserSelect's list. if removing it solved the crash i will give you a `.reg` file to rebuilt the key correctly.

---

more info:
all the keys directly under `StartMenuInternet` have a name , seen in the file as `@="BrowserName"`
but IE is missing that , so when browser select tries to display IE the name is missing (null), hence the null reference.

it is on my list to make it ignore all the malformed/incomplete records in the registry but since it only happens when registry keys have a problem it's not a bug on BrowserSelect's side.

**Comment by dogancelik** [comment]
Okay I deleted `IEXPLORER.exe` and `FirefoxPortable` and it started without errors 😃

![2016-10-14_06-03-52](https://cloud.githubusercontent.com/assets/486818/19374409/008c8e8c-91d4-11e6-802e-bab5e35c3e24.png)

Thanks!

**Comment by zumoshi** [comment]
good to know.

in case you want IE to be listed too run this `.reg` file.
https://gist.github.com/zumoshi/b8e3535018f904c42510ee3e7ca61b82
(note: if your windows is not installed in the `C:` drive edit the file before executing)
